import java.sql.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Scanner;

public class Colony {
    int colonyId;
    int mushroomTypeId;
    LocalDate startDate;
    LocalDate endDate;
    String status;
    String notes;
    Scanner ip;

    public Colony(int colonyId, int mushroomTypeId, LocalDate startDate, LocalDate endDate, String status, String notes, Scanner ip){
        this.colonyId = colonyId;
        this.mushroomTypeId = mushroomTypeId;
        this.startDate = startDate;
        this.endDate = endDate;
        this.status = status;
        this.notes = notes;
        this.ip = ip;
    }


    // factory method for creating  several Colony objects from DB data

    public static ArrayList<Colony> fromResultSetGroup(ResultSet rs, Scanner ip) throws SQLException {
        ArrayList<Colony> colonies = new ArrayList<>();

            while (rs.next()) {
                int cId = rs.getInt("colony_id");
                int mID = rs.getInt("mushroom_type_id");
                LocalDate startDate = rs.getDate("start_date").toLocalDate();

                // because endDate can be null  it needs to be checked before attempting to covert to LocalDate
                Date rawEndDate = rs.getDate("end_date");
                LocalDate endDate = (rawEndDate != null) ? rawEndDate.toLocalDate() : null;

                String status = rs.getString("status");
                String notes = rs.getString("notes");

                Colony c = new Colony(cId, mID, startDate, endDate, status, notes, ip);
                colonies.add(c);
            }

        return colonies;
    }

    // method for gathering colony details from user
    public static Colony collectColonyDetails( Scanner ip, int mushroomTypeId) {
        LocalDate startDate = LocalDate.now();
        LocalDate endDate = null;

        System.out.println("Please provide colony status 'COLONISING, FRUITING, HARVESTED, CONTAMINATED, COMPLETED'");
        String status = ip.nextLine();
        System.out.println("Please enter any relevant starting notes: ");
        String notes = ip.nextLine();
        int tempId = 0;


        // required details gathered create a new Colony
        return new Colony(tempId, mushroomTypeId, startDate, endDate, status, notes, ip);
    }

    public void insertIntoDB(DBConnect conn){
        String sql = "INSERT INTO colony (mushroom_type_id, start_date, end_date, status, notes) VALUES (?, ?, ?, ?, ?)";

        //
        try (PreparedStatement ps = conn.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, mushroomTypeId);
            ps.setDate(2, java.sql.Date.valueOf(startDate));
            // NULL check for endDate because it's a nullable value - new colony won't have an endDate yet
            // Need explicit call to java.sql because java.util.Date &  java.sql.Date  are in use.
            if (this.endDate != null) {
                ps.setDate(3, java.sql.Date.valueOf(endDate));
            } else {
                ps.setNull(3, java.sql.Types.DATE);
            }

            ps.setString(4, status);
            ps.setString(5, notes);

            ps.executeUpdate();

            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys.next()) {
                    int newId = keys.getInt(1);
                    this.colonyId = newId; // update the new colony with its autoGenerated ID so it correctly matches db
                }
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }


    public int getMushroomTypeId() {
        return mushroomTypeId;
    }

    public int getColonyId() {
        return colonyId;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public String getStatus() {
        return status;
    }

    public String getNotes() {
        return notes;
    }

    public Scanner getIp() {
        return ip;
    }
} // class end
